### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by dpacchi**
Improvements: 

- Fixed example project, 
- Support for Facebook background image, 
- Support for Facebook id in Instagram, 
- Fixed twitter sharing (url + hashtags + etc)

### CODE REVIEW

**Comment by dpacchi** [comment]
Hello @ShekarMudaliyar ,

I've fixed and improved some of the features of this asset, along with an important fix for sharing to instagram stories that will be mandatory starting Novemeber 30.

**Comment by dpacchi** [comment]
Added also

- video background support in both Facebook and Instagram
- Clipboard sharing fixes

**Comment by DennisAshford** [comment]
@ShekarMudaliyar do you plan, or expect, to merge this into the main package? The deadline for the IG story sharing is November 30th.

**Comment by kirilllapshev** [comment]
It would be really amazing if he merged this update!

**Pull request merged**
